name: mobyte_scbteamchallenge
description: Monetochka
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  animated_digit: ^3.2.1

  # navigation
  auto_route: ^5.0.1

  # state manager
  flutter_bloc: ^8.0.1

  # data classes
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  json_serializable: ^6.5.4
  web_socket_channel: ^2.2.0

  # reactive programming
  rxdart: ^0.26.0
  provider: ^6.0.2
  infinite_scroll_pagination: ^3.1.0
  appinio_swiper: ^1.0.2
  get: ^4.6.1
  fl_chart: ^0.46.0
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^19.1.54
  flutter_switch: ^0.3.2
  flutter_share: ^2.0.0
  clipboard: ^0.1.3
  fluttertoast: ^8.0.9
  accordion: ^2.2.3
  buttons_tabbar: ^1.3.4
  shared_preferences: ^2.0.13
  get_storage: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  calendar_calendar: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  auto_route_generator: ^5.0.1
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:

    - family: Gilroy_Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.otf
    - family: Gilroy_Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.otf
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf
